import { ArrowDown, Mail, Linkedin } from "lucide-react";
import { getProjects } from "@/lib/content";
import { ProjectCard } from "@/components/project-card";
import { Section } from "@/components/section";
import { Reveal } from "@/components/motion";
import { RotatingTitle } from "@/components/rotating-title";

export default function Home() {
  const projects = getProjects();
  return <main>
    <section className="hero"><div className="stars" /><div className="shell hero-grid"><Reveal><span className="availability"><i /> Available for Product, Innovation &amp; Partnerships</span><h1>RyanC</h1><p className="hero-role">A <RotatingTitle />.</p><p className="hero-copy">Designing products, building ventures, and creating meaningful experiences across technology, education, and innovation.</p><div className="actions"><a className="button primary" href="#work">View projects <ArrowDown size={15} /></a><a className="button" href="mailto:ryanchinqf2@gmail.com">Contact <Mail size={15} /></a><a className="button" href="https://www.linkedin.com/in/ryan-chin-1388961a7/" target="_blank" rel="noreferrer">LinkedIn <Linkedin size={15} /></a></div></Reveal><Reveal delay={.15}><div className="portrait-pending" aria-label="Portrait pending source asset"><span>RC</span><small>Portrait asset awaiting local recovery</small></div></Reveal></div></section>
    <Section id="work" eyebrow="01 · Selected work" title="Ideas made tangible." intro="A selection spanning product strategy, digital experiences, services, brands and physical products."><div className="project-grid">{projects.filter((project) => project.featured && project.category !== "Education").slice(0, 8).map((project, index) => <ProjectCard project={project} index={index} key={project.slug} />)}</div></Section>
    <Section id="experience" eyebrow="02 · Experience" title="Across disciplines." intro="Ryan’s work sits where product thinking, commercial opportunity and craft meet."><div className="timeline"><div className="timeline-row"><strong>Co-founder &amp; Lead Product Designer</strong><span>Alpha Electrics — product, UX and marketing leadership for light electric vehicle infrastructure.</span><span>2020—2023</span></div><div className="timeline-row"><strong>UI/UX Designer</strong><span>Singapore Airlines — digital experience concepts focused on clearer customer journeys.</span><span>2020</span></div><div className="timeline-row"><strong>Design Educator</strong><span>University-level Visual Communications and Branding — coaching emerging designers since 2021.</span><span>2021—Now</span></div></div></Section>
    <Section id="education" eyebrow="03 · Education & impact" title="Teaching sharpens practice." intro="A practice informed by industrial design training, international collaboration, and years of design education."><div className="bento"><div className="tile wide"><div><span className="eyebrow">Education</span><h3>National University of Singapore</h3></div><p>Industrial Design · A foundation in systems, research, materials and human-centred making.</p></div><div className="tile"><span className="number">3+</span><p>Years teaching visual communication and branding.</p></div><div className="tile"><span className="number">4th</span><p>Huawei Tech4City 2022, from 150 participants, for Isolert.</p></div></div></Section>
    <Section id="about" eyebrow="04 · About" title="A designer who builds." intro="RyanC is an industrial designer trained at the National University of Singapore, with expertise across UI/UX, graphic design and product design."><div className="case-copy"><p>Since 2021, education has become a meaningful part of his practice. He coaches university-level students in Visual Communications and Branding while continuing to explore the relationship between people, products and business.</p></div></Section>
    <section className="section shell" id="contact"><Reveal className="contact-card"><span className="eyebrow">Have an ambitious problem?</span><h2>Let’s make something matter.</h2><p>Available for product leadership, strategic design, collaborations and selected speaking or teaching opportunities.</p><a className="button primary" href="mailto:ryanchinqf2@gmail.com">ryanchinqf2@gmail.com <Mail size={15} /></a></Reveal></section>
  </main>;
}
