export type EditorialBeat = { title: string; copy: string; layout?: "wide" | "left" | "right" };

export const projectEditorial: Record<string, EditorialBeat[]> = {
  "alpha-electrics": [
    { title: "Mobility context", copy: "The system is shown in the context it was designed for: compact electric mobility and the infrastructure around it.", layout: "wide" },
    { title: "Battery architecture", copy: "Product views clarify how the battery, dock and supporting hardware form one connected ecosystem." },
    { title: "Power stations", copy: "Station concepts explore different footprints while retaining a consistent interaction point." },
    { title: "System communication", copy: "Diagrams and interface studies make the movement of energy and information legible." },
    { title: "Digital layer", copy: "The web and dashboard views extend the physical product into monitoring and operations." },
    { title: "Operational overview", copy: "Information is organised around status, location and the condition of deployed assets.", layout: "wide" },
    { title: "Interface detail", copy: "Supporting screens develop a restrained visual language for routine decisions." },
    { title: "Connected ecosystem", copy: "Together, the physical and digital touchpoints present Alpha Electrics as a system rather than a standalone battery." },
  ],
  "ao-chopsticks": [
    { title: "A familiar tool, reconsidered", copy: "The opening form study reframes chopsticks as a deliberate object for a contemporary table.", layout: "wide" },
    { title: "Holding gesture", copy: "In-hand views test how the integrated form changes grip, control and presentation." },
    { title: "Form development", copy: "Drawings compare profiles and details before the geometry is resolved." },
    { title: "Use", copy: "The final interaction remains recognisable while introducing a more composed dining gesture." },
  ],
  beyond: [
    { title: "An emerging context", copy: "The project frames dining as part of the wider experience of commercial space travel.", layout: "wide" },
    { title: "Designing for the journey", copy: "Editorial studies consider how luxury, ritual and practical constraints might meet beyond Earth." },
  ],
  carebox: [
    { title: "A care system", copy: "The project opens by mapping Carebox as a connected service for caregivers and families.", layout: "wide" },
    { title: "Information flow", copy: "System diagrams clarify how observations and support move between people and touchpoints." },
    { title: "Caregiver experience", copy: "Mobile interface studies focus on making daily information accessible without adding visual complexity." },
    { title: "Service touchpoints", copy: "The wider journey connects guidance, physical materials and digital communication." },
    { title: "Connected support", copy: "The final view brings the principal interactions together as one coherent care experience." },
  ],
  cyclops: [
    { title: "Character reinterpretation", copy: "The opening render establishes the silhouette, posture and material character of the sculpt.", layout: "wide" },
    { title: "Form and proportion", copy: "Alternate views reveal how mass and balance are handled across the seated figure." },
    { title: "Surface detail", copy: "Closer renders develop armour, props and smaller features without losing the larger silhouette." },
    { title: "Lighting studies", copy: "Changes in lighting test how the sculpt reads under more atmospheric conditions." },
    { title: "Profile", copy: "Side views expose relationships that are less visible from the hero angle." },
    { title: "Material separation", copy: "Distinct surfaces help organise the dense character geometry." },
    { title: "Resolved sculpt", copy: "The closing rotations present the character as a complete digital object." },
    { title: "Final view", copy: "A final perspective returns attention to the expression and overall presence.", layout: "wide" },
  ],
  "dormant-power": [
    { title: "Personal origin", copy: "The identity begins with objects and references connected to family history.", layout: "wide" },
    { title: "Geometric reduction", copy: "The mark is refined into a restrained linear form built from a small number of deliberate moves." },
    { title: "Application", copy: "Printed studies test how the identity behaves as a quiet signature rather than a loud badge." },
    { title: "Identity system", copy: "The final applications show the mark working across personal stationery and presentation materials." },
  ],
  "first-dew": [
    { title: "A fragrance ritual", copy: "The project turns fragrance into a visible moment of anticipation and release.", layout: "wide" },
    { title: "Interaction", copy: "The vessel and falling bubble create a simple sequence: wait, observe and capture." },
    { title: "Object family", copy: "Product views compare the principal components and their relationship on the table." },
    { title: "Material presence", copy: "Dark reflective surfaces make the transparent fragrance element feel more vivid." },
    { title: "Use scenario", copy: "The final composition places the ritual within a calm domestic setting." },
    { title: "Light and detail", copy: "Closing images focus on the small optical changes that give the object its sense of life." },
  ],
  ikio: [
    { title: "A new food encounter", copy: "The spatial concept separates the experience from the immediate visual associations of edible insects.", layout: "wide" },
    { title: "Experience setting", copy: "The kiosk format creates a clear sequence from curiosity to selection and tasting." },
    { title: "Interaction language", copy: "Graphic and interface studies translate unfamiliar ingredients into approachable choices." },
    { title: "Identity", copy: "The circular IKI-O mark gives the speculative experience a compact, recognisable signature." },
  ],
  isolert: [
    { title: "A visible signal", copy: "The system makes an otherwise private condition—social isolation—legible to a support network.", layout: "wide" },
    { title: "Service journey", copy: "The visual flow connects the older adult, passive signals and the people able to respond." },
    { title: "System overview", copy: "The final architecture summarises how the physical and digital elements work together." },
  ],
  "pursuit-of-balance": [
    { title: "Qi", copy: "The bedside object begins as a calm source of light whose energy comes from the phone screen.", layout: "wide" },
    { title: "Form exploration", copy: "Models investigate how the phone can be held while keeping the lamp visually quiet." },
    { title: "Refining the enclosure", copy: "Successive views move toward a softer, more continuous geometry." },
    { title: "Light behaviour", copy: "The glow is treated as part of the sleep ritual rather than a conventional notification." },
    { title: "Phone relationship", copy: "The product creates physical distance while keeping the device functionally involved." },
    { title: "Digital companion", copy: "Supporting screens extend the ritual without competing with the physical object." },
    { title: "Bedside context", copy: "The final composition shows the lamp operating as a calm threshold between device use and rest." },
    { title: "Resolved experience", copy: "Object, light and interface come together as one deliberate pre-sleep sequence.", layout: "wide" },
  ],
  "rebranding-extensions": Array.from({ length: 7 }, (_, i) => ({ title: i < 2 ? "Brand direction" : i < 5 ? "Identity applications" : "Extended system", copy: i < 2 ? "Student work reframes an existing brand through a clearer visual and narrative direction." : i < 5 ? "Applications test whether the proposed identity remains coherent across different formats and contexts." : "The final studies demonstrate how a brand idea can extend beyond a single mark into a flexible system.", layout: i === 0 ? "wide" : undefined })),
  "sia-landing-page": [
    { title: "Landing-page hierarchy", copy: "The concept focuses the opening experience around the decisions passengers need to make first.", layout: "wide" },
    { title: "Search interaction", copy: "Flight-search states simplify inputs and keep the booking task visually prominent." },
    { title: "Responsive direction", copy: "Supporting layouts maintain the same hierarchy as content and viewport conditions change." },
  ],
  "solitaire-infinity": [
    { title: "A service before arrival", copy: "Infinity positions recognition as a continuous service rather than a sequence of transactions.", layout: "wide" },
    { title: "Passport badge", copy: "The RFID object is designed to sit naturally with a passport while enabling discreet identification." },
    { title: "Journey mapping", copy: "Service diagrams connect passenger and staff touchpoints across the travel experience." },
    { title: "Interaction detail", copy: "In-hand studies focus on how the badge is carried, presented and understood." },
    { title: "Service ecosystem", copy: "The closing view brings the physical object and supporting service moments together." },
  ],
  songbird: [
    { title: "A compact companion", copy: "The stand is reduced to a lightweight loop that supports headphones without dominating the desk.", layout: "wide" },
    { title: "Structure", copy: "Repeated forms test stability, footprint and the point of contact with the headband." },
    { title: "Assembly", copy: "In-use views show the simple relationship between the stand, desk and headphones." },
    { title: "Resolved object", copy: "The final form balances portability with enough visual presence to feel intentional." },
  ],
  "synthesizing-brands": Array.from({ length: 8 }, (_, i) => ({ title: i < 2 ? "Finding a visual voice" : i < 5 ? "Building the identity" : "Brand applications", copy: i < 2 ? "The work begins by translating personal affinities into a distinct visual direction." : i < 5 ? "Typography, imagery and composition are developed into a coherent identity language." : "Applications test how each identity holds together across physical and digital formats.", layout: i === 0 ? "wide" : undefined })),
  tether: [
    { title: "Care across distance", copy: "Tether frames telemedicine as a connected home-care experience for older adults and their families.", layout: "wide" },
    { title: "Service architecture", copy: "The system map clarifies the relationship between home, clinician and supporting services." },
    { title: "Home interaction", copy: "Interface and device concepts keep common care activities direct and approachable." },
    { title: "Physical touchpoint", copy: "The product form is developed to sit comfortably within a domestic environment." },
    { title: "Connected journey", copy: "The wider sequence shows how individual interactions become a continuous care relationship." },
    { title: "System resolution", copy: "The final overview brings service, interface and physical product into one proposition." },
  ],
  "visual-literacy": Array.from({ length: 8 }, (_, i) => ({ title: i < 3 ? "Reading visual language" : i < 6 ? "Synthesis" : "Applied outcomes", copy: i < 3 ? "Students identify the visual principles that give a chosen subject its character." : i < 6 ? "The analysis is recombined into new compositions rather than reproduced literally." : "Editorial and object applications demonstrate how those principles can guide a coherent outcome.", layout: i === 0 ? "wide" : undefined })),
};
